#!/usr/bin/env node
/**
 * Generate src/generated/version.ts with the build fingerprint /__version
 * reports.
 *
 * Runs at build time (via the pre* hooks), so the values are baked into the
 * compiled output and never read at runtime.
 *
 * version and revision both resolve the same three ways:
 *   1. the environment — how Docker passes them. The build context has no
 *      .git (.dockerignore), so git cannot be asked inside the image.
 *   2. git — host and local builds.
 *   3. a default — neither available.
 *
 * package.json is deliberately not consulted. Its version has said 0.1.0 since
 * the day it was written while the tags reached v0.4.x, so reading it would
 * make this endpoint announce a release nobody can fetch. BrowserHive shipped
 * exactly that bug for months.
 */
import { execSync } from "node:child_process";
import { writeFileSync, mkdirSync } from "node:fs";

const git = (cmd) => {
  try {
    return execSync(cmd, { stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return null;
  }
};

// `describe` also covers being off a release: 0.5.0-3-gabc1234 says, out loud,
// that this build is three commits past the tag it names.
const described = process.env.GIT_TAG?.trim() || git("git describe --tags") || "unknown";

const info = {
  // `v0.5.0` is the tag name and `0.5.0` is the version; this field is the version.
  version: described.replace(/^v/, ""),
  revision: process.env.GIT_REV?.trim() || git("git rev-parse --short HEAD") || "dev",
  buildTime: new Date().toISOString(),
};

mkdirSync("src/generated", { recursive: true });
writeFileSync(
  "src/generated/version.ts",
  `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit.\n` +
    `export const BUILD_INFO = ${JSON.stringify(info, null, 2)} as const;\n`,
);

console.log("generated src/generated/version.ts", info);
